### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by shazmodan** [phamtm/rollup-plugin-i18n#1]
Hi, I'm currently trying to use this with Rollup.
`import i18n from 'rollup-plugin-i18n`

However, rollup throws an error message:
`Unexpected token export`

If I however transpile the index.js to CommonJS it works.

(This line alone generates the error)
`import i18n from 'rollup-plugin-i18n'`

For example, other rollup plugins are using CommonJS syntax:
https://github.com/TrySound/rollup-plugin-uglify/blob/master/index.js

**Comment by phamtm** [comment]
It's incorrect to import my plugin into your source code. What should be done instead is to include my plugin into your `rollup` config. Then in your source code you can use `__('some_key)` for it to be translated. 

```js
// rollup.config.js
const baseConfig = {
  format: 'es',
  plugins: [i18n({
    language: {
      'a': 'amy',
    },
  })],
};
```

**Comment by shazmodan** [comment]
It is in my rollup.config.js.
Then when I run rollup -c rollup.config.js I get the error message.

**Comment by phamtm** [comment]
I see. I have updated my plugin to use CommonJS syntax. Please upgrade to `v0.2.2`. Does it work for you?

**Comment by shazmodan** [comment]
Yes, it works now. Thank you!
